### ISSUE TITLE
Error not being raised when expected for unsafePath of `../upperfile.txt`

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [cyphar/filepath-securejoin#2]
This might be more of a question than an issue, but I'll log it anyway and see what the expectation is.

In https://github.com/cyphar/filepath-securejoin/blob/master/join.go#L61, if the values passed in to SecureJoinVFS are:

(`/root/testdir`, `../upperfile.txt`, `nil`) and on the machine the file `/root/upperfile.txt` exists, but the file `/root/testdir/upperfile.txt` does not, SecureJoinVFS() is not returning an error as I would expect.

Instead, it's cleaning up the `..` and returning (`/root/testdir/upperfile.txt`, `nil`)

If by chance I had a `/root/testdir/upperfile.txt` I still would not expect to get a pointer to it instead of `/root/upperfile.txt`.

I think the correct behavior would be to return an error in this circumstance.  Thoughts?

FWIW, this came up due to an investigation into a Podman issue logged here: https://github.com/containers/libpod/issues/5035

**Comment by TomSweeneyRedHat** [comment]
@vrothberg FYI

**Comment by cyphar** [comment]
I'll post a response both there and here -- the reasoning is that `SecureJoin` (which is soon going to be out-dated by `libpathrs`'s path handling which is race-free) is effectively acting like a `chroot`. Thus `/..` always becomes `/`.

This is necessary because there are lots of examples of malformed symlinks which only work because of this behaviour. If we made `/..` cause an error, those symlinks wouldn't work -- and it's also unclear whether absolute symlinks should also trigger the error (in the `podman build` example, the symlink will be resolved differently to the host -- and this may be confusing to some users -- but on the other hand we absolutely need to allow absolute symlinks to work because many distributions use absolute symlinks all over the place).
